development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: questionr_development
  pool: 5
  username: root
  password: hwa242

test: &test
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: questionr_test
  pool: 5
  username: root
  password: hwa242

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: questionr_production
  pool: 5
  username: root
  password: qmUn9iQ6Q6mlYWHb35yN

cucumber:
  <<: *test
